compile = gcc -Wall -g

ex1:
	$(compile) $@.c -o $@ && ./$@
ex3:
	$(compile) $@.c -o $@ && ./$@
ex6:
	$(compile) $@.c -o $@ && ./$@
ex7:
	$(compile) $@.c -o $@ && ./$@
ex8:
	$(compile) $@.c -o $@ && ./$@
ex9:
	$(compile) $@.c -o $@ && ./$@
ex10:
	$(compile) $@.c -o $@ && ./$@
ex11:
	$(compile) $@.c -o $@ && ./$@
ex12:
	$(compile) $@.c -o $@ && ./$@
ex13:
	$(compile) $@.c -o $@ && ./$@
ex14:
	$(compile) $@.c -o $@ && ./$@
ex15:
	$(compile) $@.c -o $@ && ./$@
ex16:
	$(compile) $@.c -o $@ && ./$@
ex17:
	$(compile) $@.c -o $@ && ./$@



.PHONY: clean

clean:
	rm -f ex1 ex3 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18





